[package]
name = "sync-remote"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
crossterm = "0.29.0"
html-escape = "0.2.13"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
suppaftp = { version = "^6", features = ["native-tls"] }
